version: '3.3'
services:       
    rabbitmq:
        ports: 
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "25672:25672"
            - "15671:15671"
            - "15672:15672"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
        image: rabbitmq:latest
        networks:
            - custom-network
        
    redis: 
        ports: 
            - '6379:6379'
        image: redis:latest
        networks:
            - custom-network
        
    flask-backend:
        ports: 
            - '5000:80'
        image: ba-docker-flask-backend
        restart: on-failure
        depends_on: 
            - redis
            - rabbitmq
        environment:
            - REDIS_HOST=redis
            - RABBIT_HOST=rabbitmq
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
        networks:
            - custom-network
            
    flask-services: 
        image: ba-docker-flask-services
        restart: on-failure
        environment:
            - FLASK_URL=http://flask-backend:80
            - RABBIT_HOST=rabbitmq
        networks:
            - custom-network
            
    grafana:
        ports:
            - '3000:3000'
        restart: on-failure
        volumes:
            - grafana-storage:/var/lib/grafana
        image: grafana/grafana:latest
        user: "472"
        networks:
            - custom-network
            
networks: 
    custom-network:
        driver: bridge
        name: custom-network
        
volumes:
  grafana-storage: